### ISSUE TITLE
Assignments 2 prime number 

### ISSUE THREAD

**Issue by 52bit23** [vtcbca/basic-programming-52bit23#2]
what do you mean by prime number?

**Comment by 51bit23** [comment]
A prime number is a natural number greater than 1

**Comment by 52bit23** [comment]
means every number which is grater than 1 is prime number?

**Comment by 53bit23** [comment]
@52bit23 A prime number is a number that can only be divided by 1 and itself.

**Comment by 55bit23** [comment]
@53bit23 still i didn't understand can you give me example of it!

**Comment by 53bit23** [comment]
For example, 2 and 3 are prime because they can't be divided by any other numbers. But numbers like 4, 6, and 8 are not prime because they can be divided by other numbers (like 2)

**Comment by 51bit23** [comment]
@53bit23  Exacatly what i mean.

**Comment by 55bit23** [comment]
I understand the problem!

**Comment by 55bit23** [comment]
I understand the problem!

**Comment by 52bit23** [comment]
Okay now i fully understand!

**Comment by 53bit23** [comment]
@52bit23 Okey Tell me 25 is prime number or not ?

**Comment by 52bit23** [comment]
No its not prime number cause 25 can be divided by 1, 5, and 25.

**Comment by 53bit23** [comment]
Yes! you are right.
