### ISSUE TITLE
Assignment 1 factorial 

### ISSUE THREAD

**Issue by 52bit23** [vtcbca/basic-programming-52bit23#3]
i can not understand the problem

**Comment by 54bit23** [comment]
the factorial of a number means multiplying that number by every number smaller than it down to 1.

**Comment by 52bit23** [comment]
Can you explin it in simple words with example?

**Comment by 54bit23** [comment]
For example, if we want to find 3! (3 factorial):
 3! means 3 × 2 × 1 = 6

**Comment by 52bit23** [comment]
Ok that seems fine i understand.

**Comment by 54bit23** [comment]
Now calculate the factorial of 4.

**Comment by 52bit23** [comment]
The factorial of 4 (4!) is multiply( 4 multiply 3multiply  2multiply 1 = 24 \).

**Comment by 54bit23** [comment]
Perfect!

**Comment by 52bit23** [comment]
can you tell me a Method to  solve in python?

**Comment by 54bit23** [comment]
you can use sevral types of methods like Using Recursion and  Using a Loop

**Comment by 52bit23** [comment]
Okey i will try these method to slove my problem thanks !
