### ISSUE TITLE
assignment 5 Palindrome 

### ISSUE THREAD

**Issue by 57bit23** [vtcbca/basic-programming-52bit23#4]
How do you reverse a string in Python?

**Comment by 52bit23** [comment]
Use slicing: ``reversed_string = original_string[::-1]`.`

**Comment by 57bit23** [comment]
what is string slicing in python?

**Comment by 52bit23** [comment]
Slicing in a string means extracting a part of the string by specifying a start, stop, and step using this format:`string[start:stop:step]
`

**Comment by 57bit23** [comment]
How will the output look like for the string 'VTCBCSR'?

**Comment by 52bit23** [comment]
If you slice the string 'VTCBCSR', here are some example of how the output will look:
Output: "RSCBCTV"

**Comment by 57bit23** [comment]
How to declare string in python?

**Comment by 52bit23** [comment]
n Python, you can declare a string by enclosing text in single quotes (' '), double quotes (" "), or triple quotes (''' ''' or """ """).

**Comment by 57bit23** [comment]
Thank you @57bit23 for clearing my doubts.
