### ISSUE TITLE
Assignment-3 : Fibonacci Sequence 

### ISSUE THREAD

**Issue by 52bit23** [vtcbca/basic-programming-52bit23#5]
What is the first term of the Fibonacci sequence?

**Comment by 44bit23** [comment]
The first term is 0.

**Comment by 52bit23** [comment]
How do you calculate the next term in the sequence?

**Comment by 44bit23** [comment]
Add the last two terms to get the next term.

**Comment by 52bit23** [comment]
Can the Fibonacci sequence include negative numbers?

**Comment by 44bit23** [comment]
No, the Fibonacci sequence starts with 0 and consists of non-negative numbers.

**Comment by 52bit23** [comment]
What data type can be used to store the sequence?

**Comment by 44bit23** [comment]
A list is commonly used to store the sequence in Python.

**Comment by 52bit23** [comment]
How do you generate the Fibonacci sequence for a fixed number of terms?

**Comment by 44bit23** [comment]
Use a loop to calculate and store terms until the desired count is reached.

**Comment by 52bit23** [comment]
Thank you for helping me @44bit23 .
