### ISSUE TITLE
Assignment-4 : Reverse String

### ISSUE THREAD

**Issue by 46bit23** [vtcbca/basic-programming-52bit23#6]
What does it mean to reverse a string?

**Comment by 52bit23** [comment]
Reversing a string means arranging its characters in the opposite order. For example, "hello" becomes "olleh".

**Comment by 46bit23** [comment]
What data type is used for strings in Python?

**Comment by 52bit23** [comment]
Strings in Python are of type str.

**Comment by 52bit23** [comment]
Which Python function can be used to take user input for a string?

**Comment by 46bit23** [comment]
Which Python function can be used to take user input for a string?

**Comment by 52bit23** [comment]
Use the input() function:

`string = input("Enter a string: ")`

**Comment by 46bit23** [comment]
What is string slicing?

**Comment by 52bit23** [comment]
String slicing in Python means extracting a part (or "slice") of a string using its position (index). You specify the start, stop, and step values inside square brackets. For example:  
```python
substring = string[1:4]  # Gets characters from index 1 to 3.
```  
It's a way to work with only specific parts of a string.

**Comment by 46bit23** [comment]
How do you reverse a string in Python using slicing?

**Comment by 52bit23** [comment]
Use slicing with a step of -1:
python

`reversed_string = string[::-1]`

**Comment by 46bit23** [comment]
its gonna help me in python programming thanks @46bit23
